import type { Metadata } from "next";
import { siteConfig } from "@/lib/site-config";

/** A full address on this site, e.g. absoluteUrl("/about") -> https://www.driptoseed.com/about */
export const absoluteUrl = (path = "/"): string => `${siteConfig.url}${path === "/" ? "" : path}`;

/** The shared social-preview image (generated by app/opengraph-image.tsx). */
export const defaultShareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name}: ${siteConfig.tagline}. Clipping, seeding and distribution for creators.`,
};

type PageSeo = {
  /** The page title. The site name is added after it ("About Us | Drip") unless `absoluteTitle` is true. */
  title: string;
  absoluteTitle?: boolean;
  /** 120 to 158 characters reads best in search results. */
  description: string;
  /** The page's path, e.g. "/about". Becomes the canonical address and the shared link. */
  path: string;
  /** A social-preview image for this page. Defaults to the site-wide one. */
  image?: { url: string; width?: number; height?: number; alt: string };
  type?: "website" | "article";
  /** Keep the page out of search results (it is still crawled so the instruction is seen). */
  noindex?: boolean;
};

/**
 * Everything a page needs to look right in search results and when its link is shared: title, description,
 * canonical address, Open Graph (Facebook, LinkedIn, WhatsApp...) and Twitter/X cards.
 *
 * Next.js replaces (it does not merge) the layout's openGraph and twitter objects when a page sets its own, so each
 * page has to carry the full set, including the image. This builds all of it in one place so none is forgotten.
 */
export function pageMetadata({ title, absoluteTitle, description, path, image, type = "website", noindex }: PageSeo): Metadata {
  const share = image ?? defaultShareImage;
  const fullTitle = absoluteTitle ? title : `${title} | ${siteConfig.name}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type,
      url: path,
      siteName: siteConfig.name,
      title: fullTitle,
      description,
      locale: "en_US",
      images: [{ url: share.url, width: share.width ?? 1200, height: share.height ?? 630, alt: share.alt }],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [{ url: share.url, alt: share.alt }],
    },
  };
}
